<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UseWPF>true</UseWPF>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <GenerateTargetFrameworkAttribute>false</GenerateTargetFrameworkAttribute>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="CustomResoManager.McpServer\**" />
    <None Remove="CustomResoManager.McpServer\**" />
    <EmbeddedResource Remove="CustomResoManager.McpServer\**" />
    <Page Remove="CustomResoManager.McpServer\**" />
  </ItemGroup>

</Project>
